name: Big Bang Deployment

on:
  workflow_dispatch:
    inputs:
      target_app:
        description: 'Target App (blue/green)'
        required: true
        default: 'blue'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore *.sln

    - name: Build
      run: dotnet build *.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish *.sln -c Release -o ../out
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: formation-eshop-${{ github.event.inputs.target_app }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./out
